spring:
  application:
    name: save-the-was
  datasource:
    url: jdbc:mysql://localhost:3306/labdb?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&rewriteBatchedStatements=true
    username: lab
    password: labpw
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
